import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import AvNavbar from "@/components/AvNavbar";
import AvFooter from "@/components/AvFooter";
import layoutStyles from "@/styles/layout.module.css"


export const metadata: Metadata = {
  title: "Ariventures",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={layoutStyles.wrapper}>
        <AvNavbar/>
        <main className={layoutStyles.main}>
          {children}
        </main>
        <AvFooter/>
      </body>
    </html>
  );
}
